In [16]:
# What is numpy in Python?   https://www.w3schools.com/python/numpy/numpy_intro.asp

# Answer:  NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.


# What is an array?
# An array is a common type of data structure wherein all elements must be of the **same data type**,
# such as integers or floating point values.

# What is the difference between lists and arrays in Python?
# Python arrays and lists have the same way of storing data but the key difference between them is that 
#lists can store **any type of data** whereas arrays store single data type elements.
#And because of this difference, other than a few operations like sorting and looping,
#operations performed on these data structures are different

# The array object in NumPy is called ndarray
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists


In [3]:
import numpy  as np  # NumPy is usually imported under the np alias.


In [4]:
print(np.__version__)  #  The version string is stored under __version__ attribute.

1.15.4


In [5]:
#****1.  Creating numpy array
# To create an ndarray, we can pass(cast) a list, tuple or any array-like object into the array() method,
#and it will be converted into an ndarray:

In [6]:
T= ( 1,2,3)  # pass a tuple into the array() method to convert it into an ndarray
print(np.array(T))

[1 2 3]


In [7]:
type(np.array(T))   # type(): This built-in Python function tells us the type of the object passed to it

numpy.ndarray

In [8]:
# Dimensions in Arrays: 0, 1,2,3,..n.
# A dimension in arrays is one level of array depth (nested arrays).

# nested array: are arrays that have arrays as their elements.

In [9]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)     # array.ndim a dimension attribute
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
print(a)
print(b)
print(c)
print(d)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# ndmin argument could specify the n dimension of an array ( the shape of an array)

In [12]:
arr = np.array([1, 2, 3, 4], ndmin=5)  # argumenbt ndim is 5

print(arr)
print('number of dimensions :', arr.ndim)  # Or you can call "the shape of the array": 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [33]:
D= {"A": 2, "B": 3, "C": 4} # pass a dictionary to a numpy array
print(type(D))
print(np.array(D)) # dictionary is not an array because it dosent contain the "same data type": integer or float
type(np.array(D))   # check the data type


<class 'dict'>
{'A': 2, 'B': 3, 'C': 4}


numpy.ndarray

In [14]:
# *** 2. Create numpy array: Use some python's own builtin generation methods to actually create

# arrays a lot faster and a lot simpler.
# ** np.arange(start, stop, step size, dtype=)  3 arguments and dataatype and  return evenly spaced

# values within this given interval. similar to the python's builtin function range

In [15]:
A = np.arange(1,10)  # Create a one dimension numpy array with numbers from 1 to 9 ( last number is excluded)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
B= np.arange(0,50,5)  # create a numpy array from 0 to 49 with step number 5
B

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
C= np.arange( 0, 30) # a range is going to be one of the most useful functions for quickly generating an array
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
E= C.reshape(5,6) 
E
# use reshape Reshaping arrays
#Reshaping means changing the shape of an array.

#The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
# ****Creating arrays with pecific types of arrays
# np.zeros(shapes)  an array with all zeros as elements
# np.ones((2,3))  a 2x3 array with 1 as elements in 2 rows and 3 columns dimension = 6
# np.eye((3)) a 3x3 identity array
# np.linspace(start, stop,)

In [48]:
arr_z= np.zeros(5)

print(arr_z.ndim)
arr_z

1


array([0., 0., 0., 0., 0.])

In [52]:
print(np.zeros((2,2)))  # 2x2 shape
np.zeros((2,2)).ndim  # dimension


[[0. 0.]
 [0. 0.]]


2

In [53]:
np.ones(5)  # ones array 1 dimesion  shape 1x1

array([1., 1., 1., 1., 1.])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.ones((2,3)).ndim # dimensions of the array is 2

2

In [56]:
np.ones((2,3)).shape  # shape of the array is 2x3

(2, 3)

In [57]:
type(np.ones((2,3)))  # type of the array is numpy ndarray

numpy.ndarray

In [59]:
np.eye(3)  # one argument in the identity function 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.eye(5).shape

(5, 5)

In [63]:
np.eye(2).ndim

2

In [ ]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [64]:
np.linspace(1,5) # generate any number of array between 1 to 5

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [65]:
np.linspace(1,5).ndim

1

In [66]:
np.linspace(1,5,10)  # 10 of the elements in the array between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
L=np.linspace(1,5,10, endpoint=False)  # endpoint = 5 is not included
L

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [70]:
np.linspace(1,5,10).reshape((2,5))

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [71]:
# #we can also print the other attributes like dimensions,shape and size of an array
print ("Dimensions of a are:", L.ndim)
print ("Shape of a is", L.shape)
print ("Size of a is", L.size)

Dimensions of a are: 1
Shape of a is (10,)
Size of a is 10


In [72]:
# Creating an Empty Array using empty_like Function
# np.empty() creates an array with random values
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
Empty_arr=np.empty([3,5])
Empty_arr

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313,
        1.48539705e-313, 1.90979621e-313],
       [2.33419537e-313, 2.75859453e-313, 3.18299369e-313,
        3.60739285e-313, 4.03179200e-313],
       [4.45619116e-313, 4.88059032e-313, 5.30498948e-313,
        5.72938864e-313, 6.15378780e-313]])

In [77]:
print ("Dimensions of a are:", Empty_arr.ndim)
print ("Shape of a is", Empty_arr.shape)
print ("Size of a is", Empty_arr.size)

Dimensions of a are: 2
Shape of a is (3, 5)
Size of a is 15


In [ ]:
# ***4. Create an array with random number of normal distribution from 0 to 1, excludes 1
# np.random.rand(5) # one dimensional
# random.rand(d0, d1, ..., dn), do, d1...denotes  dimension 0, 1,2 and so on 
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

#Parameters
#d0, d1, …, dnint, optional
#The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

#Returns outndarray, shape (d0, d1, ..., dn) Random values.

In [ ]:
# ***The random module's np.random.rand() method returns a random float between 0 and 1.

In [78]:
 np.random.rand(5) # dimension 0 with random numbers 5

array([0.60555554, 0.68544551, 0.22471954, 0.37563266, 0.05550229])

In [79]:
 np.random.rand(5)

array([0.00633183, 0.44608817, 0.09246434, 0.15410228, 0.95761217])

In [80]:
 np.random.rand(5)

array([0.29586566, 0.80719549, 0.34600593, 0.46287725, 0.3308647 ])

In [ ]:
# Each time when you run  np.random.rand(5) it will give you a different array of 5 elements between 0 and 1 , 1 excluded

In [85]:
Rand_arr =np.random.rand(2, 10) # 2x10 dimensional array with 10 numbers  between 0 and 1
Rand_arr

array([[0.64728281, 0.027296  , 0.78069453, 0.86660157, 0.37927562,
        0.80452672, 0.56381252, 0.72371908, 0.63611694, 0.92092304],
       [0.99702346, 0.55512033, 0.75424574, 0.84774588, 0.44141884,
        0.58526852, 0.40383616, 0.94766394, 0.92469007, 0.21583846]])

In [86]:
print ("Dimensions of a are:", Rand_arr.ndim)
print ("Shape of a is", Rand_arr.shape)
print ("Size of a is", Rand_arr.size)

Dimensions of a are: 2
Shape of a is (2, 10)
Size of a is 20


In [88]:
Rand_arr1=np.random.rand(2, 3,5) # 2 x3x5
Rand_arr1

array([[[0.46946294, 0.04097358, 0.50680646, 0.3299735 , 0.0272092 ],
        [0.02864293, 0.93137537, 0.42103995, 0.9626721 , 0.90591274],
        [0.49565024, 0.4530234 , 0.86433521, 0.06571435, 0.58729417]],

       [[0.66695402, 0.68921693, 0.19014806, 0.84258494, 0.678254  ],
        [0.22820988, 0.32734721, 0.68882011, 0.28618375, 0.66453581],
        [0.54994026, 0.31827055, 0.54546603, 0.15382575, 0.24422076]]])

In [89]:
print ("Dimensions of a are:", Rand_arr1.ndim)
print ("Shape of a is", Rand_arr1.shape)
print ("Size of a is", Rand_arr1.size)

Dimensions of a are: 3
Shape of a is (2, 3, 5)
Size of a is 30


In [90]:
Rand_arr2=np.random.rand(2, 3,5,4)
Rand_arr2

array([[[[0.4353628 , 0.18911564, 0.14940136, 0.90877959],
         [0.42443005, 0.42097747, 0.7948502 , 0.54690651],
         [0.95378901, 0.09699627, 0.19997487, 0.92476504],
         [0.37532291, 0.11857171, 0.9336332 , 0.33955927],
         [0.63276793, 0.08771963, 0.6188693 , 0.47812951]],

        [[0.84738559, 0.01170842, 0.11645009, 0.41478797],
         [0.98702858, 0.84357922, 0.10206353, 0.2235016 ],
         [0.12219116, 0.9429809 , 0.37683033, 0.53992092],
         [0.6489942 , 0.23628226, 0.92981968, 0.07475976],
         [0.51848761, 0.72327331, 0.16605242, 0.24065648]],

        [[0.5270125 , 0.03855447, 0.82952914, 0.77857033],
         [0.18134829, 0.79942984, 0.18316608, 0.2423024 ],
         [0.79510374, 0.60493944, 0.23981377, 0.14400941],
         [0.88415091, 0.37330848, 0.20313103, 0.24901192],
         [0.22559612, 0.23213603, 0.45797371, 0.5979415 ]]],


       [[[0.13652156, 0.53348084, 0.93995719, 0.29196123],
         [0.44973465, 0.47928741, 0.94597809, 0.

In [91]:
print ("Dimensions of a are:", Rand_arr2.ndim)
print ("Shape of a is", Rand_arr2.shape)
print ("Size of a is", Rand_arr2.size)

Dimensions of a are: 4
Shape of a is (2, 3, 5, 4)
Size of a is 120


In [ ]:
# np.random.randn()
#random.randn(d0, d1, ..., dn)
#Return a sample (or samples) from the “standard normal” distribution.
#Parameters
#d0, d1, …, dnint, optional
#The dimensions of the returned array, must be non-negative. 
#If no argument is given a single Python float is returned.

#Returns
#ndarray or float
# A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, 
#or a single such float if no parameters were supplied.

#Note:  randn generates an array of shape (d0, d1, ..., dn), 
#filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [92]:
# Example:
np.random.randn()

-0.11564115014063812

In [93]:
np.random.randn(2)

array([ 0.54657395, -1.45001799])

In [94]:
np.random.randn(2,3,4)

array([[[ 2.68440165, -1.23745532, -0.81526339, -1.08426572],
        [ 0.77363662,  0.59023776, -0.17138664, -1.77800118],
        [-1.3170528 ,  0.07665084, -0.74645454,  0.24311972]],

       [[-0.90835442, -0.63310693,  0.3701049 ,  0.57529729],
        [-1.88299385,  0.55243506,  0.14061614,  0.95661352],
        [-0.6906565 , -0.1913332 , -1.27942191, -0.71299463]]])

In [ ]:
# The np.random.randint(num,size=) method takes a size parameter where you can specify the shape of an array.

In [108]:
Randint_arr=np.random.randint(10,size=(2,2)) # generate any 10 numbers of size 2x2
Randint_arr

array([[5, 5],
       [2, 3]])

In [109]:
print ("Dimensions of a are:", Randint_arr.ndim)
print ("Shape of a is", Randint_arr.shape)
print ("Size of a is", Randint_arr.size)

Dimensions of a are: 2
Shape of a is (2, 2)
Size of a is 4


In [110]:
Randint_arr1=np.random.randint(20, size=(2,3,2))
Randint_arr1

array([[[ 2, 19],
        [16, 14],
        [ 7,  1]],

       [[16, 16],
        [16, 13],
        [ 3,  5]]])

In [111]:
print ("Dimensions of a are:", Randint_arr1.ndim)
print ("Shape of a is", Randint_arr1.shape)
print ("Size of a is", Randint_arr1.size)

Dimensions of a are: 3
Shape of a is (2, 3, 2)
Size of a is 12


In [112]:
np.random.randint(50) # return one number of the range up to 50

41

In [113]:
np.arange(50) # return 50 numbers up to 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [116]:
np.arange(50)

array([], dtype=int32)

In [118]:
np.random.choice([1,2,3,4],size=(2,3))
# the choice method generates a ramdom array with one number/numbers
# out of the given list with the given size

array([[3, 2, 2],
       [2, 2, 3]])

In [121]:
np.random.choice(30, size=(2,2)) # return a random number/or array from 0 to 30 similar to randint method

array([[20, 14],
       [21, 26]])

In [122]:
np.random.randint(30, size=(2,2)) # return a random array from 0 to 30 with size =(2,2)

array([[22,  4],
       [ 2, 10]])