# ***Numpy array operations
## 1.Array with array
## 2.Array with scalars
## 3.Array with universal functions ufunc

In [1]:
import numpy as np

## 1.  Simple arrays  arithmetics operations: +, -, * , / ,//,  %, ** ( power)

### operations on corresponding elements(same index) from each array


In [2]:
#create an array

arr=np.arange(5,30)  # arange(lower,higher)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
arr+arr   # addition

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58])

In [4]:
arr-arr  # subtration

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [5]:
arr*arr  # multiplication 

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841])

In [6]:
arr/arr # division

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr%arr  # modulus  5%2= 1  3%3=0 remainder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int32)

In [8]:
arr// arr # Floor division = the whole number 5/2= 2 , 10//3= 3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int32)

In [9]:
5//2

2

In [10]:
arr**arr

array([       3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989,
                 0,   878082373,   977272832, -1276351769,           0,
        1296002393,   603979776,  -714244925,           0, -1266004979],
      dtype=int32)

In [11]:
arr**2

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289,
       324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841],
      dtype=int32)

## 2. Arrays with scalars

### each element from the array operates with the scalar 

In [12]:
arr+2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31])

In [13]:
arr-7

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22])

In [14]:
arr/5

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])

In [15]:
arr*-1

array([ -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16, -17,
       -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29])

In [16]:
5/arr

array([1.        , 0.83333333, 0.71428571, 0.625     , 0.55555556,
       0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286,
       0.33333333, 0.3125    , 0.29411765, 0.27777778, 0.26315789,
       0.25      , 0.23809524, 0.22727273, 0.2173913 , 0.20833333,
       0.2       , 0.19230769, 0.18518519, 0.17857143, 0.17241379])

In [17]:
arr/0

C:\Users\cheng\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [18]:
0/arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr//3

array([1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8,
       9, 9, 9], dtype=int32)

In [20]:
arr% 5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4], dtype=int32)

In [21]:
arr** 1/2

array([ 2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,
        8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. ,
       13.5, 14. , 14.5])

##  3. Array with universal functions ufunc

In [22]:
# Create array with linspace(start,stop, num, endpoint=false)

In [23]:
from numpy.random import randint
from numpy.random import choice
# we will use choice function to create arrays

In [24]:
X= choice(20,(4,5)) # create a 4x5 array of any number up to 20 
Y= choice(20, (4,5))
print("X= ", X)
print("Y= ", Y)

X=  [[17 10  3  3 13]
 [13  7 14 15 13]
 [ 5 19  5  3 12]
 [ 8 14 12  9  6]]
Y=  [[17 16 15 12  0]
 [13  2 15  6 14]
 [18  5 16  2  7]
 [ 0  5 13 15  4]]


In [25]:
X+Y 

array([[34, 26, 18, 15, 13],
       [26,  9, 29, 21, 27],
       [23, 24, 21,  5, 19],
       [ 8, 19, 25, 24, 10]])

In [26]:
 # addition can use np.add() function The add() funct to sum the content of two arrays, and return the results in a new array.
Add= np.add(X,Y)
Add

array([[34, 26, 18, 15, 13],
       [26,  9, 29, 21, 27],
       [23, 24, 21,  5, 19],
       [ 8, 19, 25, 24, 10]])

In [27]:
# The np.subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.
Sub=np.subtract(X,Y)
Sub

array([[  0,  -6, -12,  -9,  13],
       [  0,   5,  -1,   9,  -1],
       [-13,  14, -11,   1,   5],
       [  8,   9,  -1,  -6,   2]])

In [28]:
# np.multiply() for multiplication
Mult=np.multiply(X,Y)
Mult

array([[289, 160,  45,  36,   0],
       [169,  14, 210,  90, 182],
       [ 90,  95,  80,   6,  84],
       [  0,  70, 156, 135,  24]])

In [29]:
# np.divide()
Div=np.divide(X,Y)
Div

C:\Users\cheng\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[1.        , 0.625     , 0.2       , 0.25      ,        inf],
       [1.        , 3.5       , 0.93333333, 2.5       , 0.92857143],
       [0.27777778, 3.8       , 0.3125    , 1.5       , 1.71428571],
       [       inf, 2.8       , 0.92307692, 0.6       , 1.5       ]])

In [30]:
# The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.
Pow=np.power(X,2)
Pow

array([[289, 100,   9,   9, 169],
       [169,  49, 196, 225, 169],
       [ 25, 361,  25,   9, 144],
       [ 64, 196, 144,  81,  36]], dtype=int32)

In [31]:
# Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array
Mod= np.mod(Y,5)  # same as Y%5
Mod

array([[2, 1, 0, 2, 0],
       [3, 2, 0, 1, 4],
       [3, 0, 1, 2, 2],
       [0, 0, 3, 0, 4]], dtype=int32)

In [32]:
Remainder= np.remainder(X,Y)
Remainder

C:\Users\cheng\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[ 0, 10,  3,  3,  0],
       [ 0,  1, 14,  3, 13],
       [ 5,  4,  5,  1,  5],
       [ 0,  4, 12,  9,  2]], dtype=int32)

In [33]:
# The divmod() function return both the quotient and the the mod. The return value is two arrays,
# the first array contains the quotient and second array contains the mod.

Divmod=np.divmod(X,4)
Divmod

(array([[4, 2, 0, 0, 3],
        [3, 1, 3, 3, 3],
        [1, 4, 1, 0, 3],
        [2, 3, 3, 2, 1]], dtype=int32), array([[1, 2, 3, 3, 1],
        [1, 3, 2, 3, 1],
        [1, 3, 1, 3, 0],
        [0, 2, 0, 1, 2]], dtype=int32))

In [34]:
# Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's
# inbuilt math.abs()

abs= np.abs(-X)
abs

array([[17, 10,  3,  3, 13],
       [13,  7, 14, 15, 13],
       [ 5, 19,  5,  3, 12],
       [ 8, 14, 12,  9,  6]])

In [35]:
abs=np.absolute([-3,0,-5,6])
abs

array([3, 0, 5, 6])

In [40]:
arr=randint(3,8, (2,3)) # a 2x3 array from numbers between 3 and 7
arr

array([[3, 6, 4],
       [7, 6, 5]])

In [41]:
Arang=np.arange(3,20)

In [42]:
# sort() function  np.sort(arr) will sort numbers from small to big or strings althabetically  
np.sort(arr)

array([[3, 4, 6],
       [5, 6, 7]])

In [43]:
np.sort(["Alice", "Jenny", "Michael", "Brian"])

array(['Alice', 'Brian', 'Jenny', 'Michael'], dtype='<U7')

###  More Ufunc:
####  1. Rounding Decimals: trunc() and fix(), around(), floor(), ciel()
#### 2. Python Logs: log2(). log10(),log(), fromfunc(log,2,1)
#### 3. summation, product and difference
####  4. LCM and GCD
####  5. Trig functions

####  1. Rounding decimals: 
####  np.trunc(array) or np.fix(array) cut off the decimals



In [71]:
trunc=np.trunc([2.26, 3.6])  # return a float
print(trunc)
print(trunc.dtype)

[2. 3.]
float64


In [47]:
np.fix(-5.87)

-5.0

In [51]:
# np.around(num, decimal place) returns a rounded number up if >=5
np.around(3.251, 2) # round it to the nearest 2

3.25

In [65]:
Arr=np.random.randn(5)
Arr

array([-0.27875693,  2.20818388, -0.4173372 ,  1.25461455, -0.14225006])

In [67]:
Arr.size

5

In [69]:
np.round(Arr,3) # round the array to the nearest 3

array([-0.279,  2.208, -0.417,  1.255, -0.142])

###  np.floor(), ceil()  get the integer 
#### The floor() function rounds off decimal to nearest lower float
#### The ceil() function rounds off decimal to nearest upper float



In [76]:
np.floor(-4.02)  # -5<-4.02

-5.0

In [78]:
np.floor(2.56)  # 2< 2.56

2.0

In [74]:
np.ceil(-3.02)  # -3>-3.02

-3.0

In [75]:
np.floor(-3.02)

-4.0

In [77]:
np.dtype(np.floor(-3.02))

dtype('float64')

####  2. Python Logs: log2(). log10(),log(), fromfunc(log,2,1)¶

In [79]:
# base 2 log
np.log2(4)

2.0

In [80]:
# base 10 log  np.log10()
np.log10(100)

2.0

In [85]:
# base e natural log  np.log()
np.log(2.71828)# e= 2.71828..

0.999999327347282

In [87]:
import math 
math.log(25,5)  # math.log(number, base 5**2=25

2.0

####  3. summation, product and difference
####  summation np.sum(): add up all elements in the array or add up in each array if axis=1 (column)
#### np.cumsum: Cummulative sum means partially adding the elements in array. 
#### difference: np.diff()  A discrete difference means subtracting two successive elements  
####  np,diff(array, 2) subtract 2 times 
####  products: np.prod() np.cumprod() similar to summation and cumsum


In [94]:
# Summation and cumsum
np.sum(np.array([1,2,3,4])) # 1+2+3+4

10

In [95]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,6,7])

In [96]:
np.add(arr1,arr2) # add the corresponding elements 

array([ 4,  6,  9, 11])

In [98]:
np.sum([arr1,arr2])  # sum up all elements with axis=0

30

In [99]:
np.sum([arr1,arr2],axis=1) # sum up each array respectively along column when axis= 1

array([10, 20])

In [101]:
np.cumsum(arr1)  # =[1,1+2,1+2+3,1+2+4] partially add up elements in array

array([ 1,  3,  6, 10], dtype=int32)

In [102]:
np.cumsum([arr1,arr2]) # add up all elements partially

array([ 1,  3,  6, 10, 13, 17, 23, 30], dtype=int32)

In [103]:
np.cumsum([arr1,arr2],axis=1)

array([[ 1,  3,  6, 10],
       [ 3,  7, 13, 20]], dtype=int32)

In [104]:
# differences
np.diff(arr1)  # discrete diff means subtracting two successive elements =[2-1,3-2,4-3], one less  element 

array([1, 1, 1])

In [107]:
np.diff([arr1,arr2]) axis = 0 or 1 will return the same result because the discrete diff performs on its own array

array([[1, 1, 1],
       [1, 2, 1]])

In [108]:
np.diff(arr1,2) # subtracted two times first=[2-1,3-2,4-3] 2nd=[1-1,1-1]

array([0, 0])

In [109]:
# products
np.prod(arr1) # multiply all elements 1*2*3*4

24

In [110]:
np.prod([arr1,arr2]) multiply all elements from both arrays

12096

In [111]:
np.prod([arr1,arr2],axis=1) # perform along columns( array)(if  axis=1)

array([ 24, 504])

In [112]:
np.cumprod(arr1)  # partially multiply =[1,1*2,1*2*3,1*2*3*4]

array([ 1,  2,  6, 24], dtype=int32)

In [114]:
np.cumprod([arr1,arr2],axis=1)

array([[  1,   2,   6,  24],
       [  3,  12,  72, 504]], dtype=int32)

####  4. LCM and GCD
#### LCM: np.lcm(arr) The Lowest Common Multiple is the least number that is common multiple of both of the numbers
#### np.lcm.reduce(arr): The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension
#### GCD:np.gcd(arr): The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers
#### np.gcd.reduce(arr)  The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension

In [116]:
# LCM and reduced LCM  only for 2 memebers (number or arrays )
np.lcm(2,3)

6

In [126]:
np.lcm(arr1,arr2)

array([ 3,  4,  6, 28])

In [118]:
np.lcm.reduce(arr1)  # LCM for all elements in an array

12

In [131]:
np.lcm.reduce([arr1,arr2])  # deal with elements of the same index respectively reduce it to one dim

array([ 3,  4,  6, 28])

In [119]:
arr3= np.arange(1,11) # gerenate an array from 1 to 11 endpoint is not included
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
np.lcm.reduce(arr3)

2520

In [121]:
# GCD  
np.gcd(5,20)

5

In [124]:
np.gcd([2,3,5],[4,9,10])

array([2, 3, 5])

In [125]:
np.gcd(arr1,arr2)  # arrays shapes are the same so it could find the gcd of two elements with the same index from each array

array([1, 2, 3, 1])

In [128]:
np.gcd(arr1,arr3)  # arrays shapes  are not the same 

ValueError: operands could not be broadcast together with shapes (4,) (10,) 

In [133]:
np.gcd.reduce(arr1,arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [134]:
np.gcd.reduce([arr1,arr2])

array([1, 2, 3, 1])

### Trigonometric Functions
#### NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [136]:
# pi/2 =90degree 
np.sin(np.pi/2)

1.0

In [137]:
# Find sine values for all of the values in arr:
arr=np.array([np.pi/2,np.pi/4, np.pi/3, np.pi])
x=np.cos(arr)
x

array([ 6.12323400e-17,  7.07106781e-01,  5.00000000e-01, -1.00000000e+00])

In [138]:
# Convert Degrees Into Radians or wise versa
arr=np.array([90,45,180])
x=np.deg2rad(arr)
x

array([1.57079633, 0.78539816, 3.14159265])

In [139]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [ ]:
# Finding angles
#Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

# NumPy provides ufuncs arcsin(), arccos() and arctan() 
# that produce radian values for corresponding sin, cos and tan values given.

In [140]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)  # angles in radiant

[ 1.57079633 -1.57079633  0.10016742]


In [141]:
np.rad2deg(x)

array([ 90.        , -90.        ,   5.73917048])

In [ ]:
# Hypotenues
#Finding hypotenues using pythagoras theorem in NumPy.

# NumPy provides the hypot() function that takes the base and perpendicular values and
# produces hypotenues based on pythagoras theorem. a**2+b**2=h**2

In [143]:
a= 2
b=3
np.hypot(a,b)

3.605551275463989

####  set: collection with unique elements
#Create Sets in NumPy
#We can use NumPy's unique() method to find unique elements from any array. E.g.
#create a set array, but remember that the set arrays should only be 1-D arrays.# 

In [152]:
arr1=np.array ([1,1,2,2,3,4,5,3])
arr2=np.array([1,1,3,3,4,6,5,4,7])
U=np.unique(arr1)
U

array([1, 2, 3, 4, 5])

In [155]:
type(U)

numpy.ndarray

In [156]:
# np.union1d() to find the union of unique elements
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [157]:
# To find only the values that are present in both arrays, use the intersect1d() method
np.intersect1d(arr1,arr2)

array([1, 3, 4, 5])