In [16]:
# What is numpy in Python?   https://www.w3schools.com/python/numpy/numpy_intro.asp

# Answer:  NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.


# What is an array?
# An array is a common type of data structure wherein all elements must be of the **same data type**,
# such as integers or floating point values.

# What is the difference between lists and arrays in Python?
# Python arrays and lists have the same way of storing data but the key difference between them is that 
#lists can store **any type of data** whereas arrays store single data type elements.
#And because of this difference, other than a few operations like sorting and looping,
#operations performed on these data structures are different

# The array object in NumPy is called ndarray
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists


In [2]:
import numpy  as np  # NumPy is usually imported under the np alias.


In [3]:
print(np.__version__)  #  The version string is stored under __version__ attribute.

1.15.4


In [4]:
#****1.  Creating numpy array
# To create an ndarray, we can pass(cast) a list, tuple or any array-like object into the array() method,
#and it will be converted into an ndarray:

In [5]:
T= ( 1,2,3)  # pass a tuple into the array() method to convert it into an ndarray
print(np.array(T))

[1 2 3]


In [6]:
type(np.array(T))   # type(): This built-in Python function tells us the type of the object passed to it

numpy.ndarray

In [7]:
# Dimensions in Arrays: 0, 1,2,3,..n.
# A dimension in arrays is one level of array depth (nested arrays).

# nested array: are arrays that have arrays as their elements.

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)     # array.ndim a dimension attribute
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
print(a)
print(b)
print(c)
print(d)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
# ndmin argument could specify the n dimension of an array ( the shape of an array)

In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)  # argumenbt ndim is 5

print(arr)
print('number of dimensions :', arr.ndim)  # Or you can call "the shape of the array": 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
D= {"A": 2, "B": 3, "C": 4} # pass a dictionary to a numpy array
print(type(D))
print(np.array(D)) # dictionary is not an array because it dosent contain the "same data type": integer or float
type(np.array(D))   # check the data type


<class 'dict'>
{'A': 2, 'B': 3, 'C': 4}


numpy.ndarray

In [13]:
# *** 2. Create numpy array: Use some python's own builtin generation methods to actually create

# arrays a lot faster and a lot simpler.
# ** np.arange(start, stop, step size, dtype=)  3 arguments and dataatype and  return evenly spaced

# values within this given interval. similar to the python's builtin function range

In [14]:
A = np.arange(1,10)  # Create a one dimension numpy array with numbers from 1 to 9 ( last number is excluded)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
B= np.arange(0,50,5)  # create a numpy array from 0 to 49 with step number 5
B

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
C= np.arange( 0, 30) # a range is going to be one of the most useful functions for quickly generating an array
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
E= C.reshape(5,6) 
E
# use reshape Reshaping arrays
#Reshaping means changing the shape of an array.

#The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
# ****Creating arrays with pecific types of arrays
# np.zeros(shapes)  an array with all zeros as elements
# np.ones((2,3))  a 2x3 array with 1 as elements in 2 rows and 3 columns dimension = 6
# np.eye((3)) a 3x3 identity array
# np.linspace(start, stop,)

In [19]:
arr_z= np.zeros(5)

print(arr_z.ndim)
arr_z

1


array([0., 0., 0., 0., 0.])

In [20]:
print(np.zeros((2,2)))  # 2x2 shape
np.zeros((2,2)).ndim  # dimension


[[0. 0.]
 [0. 0.]]


2

In [21]:
np.ones(5)  # ones array 1 dimesion  shape 1x1

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((2,3)).ndim # dimensions of the array is 2

2

In [24]:
np.ones((2,3)).shape  # shape of the array is 2x3

(2, 3)

In [25]:
type(np.ones((2,3)))  # type of the array is numpy ndarray

numpy.ndarray

In [26]:
np.eye(3)  # one argument in the identity function 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(5).shape

(5, 5)

In [28]:
np.eye(2).ndim

2

In [29]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [30]:
np.linspace(1,5) # generate any number of array between 1 to 5

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [31]:
np.linspace(1,5).ndim

1

In [32]:
np.linspace(1,5,10)  # 10 of the elements in the array between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
L=np.linspace(1,5,10, endpoint=False)  # endpoint = 5 is not included
L

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [34]:
np.linspace(1,5,10).reshape((2,5))

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [35]:
# #we can also print the other attributes like dimensions,shape and size of an array
print ("Dimensions of a are:", L.ndim)
print ("Shape of a is", L.shape)
print ("Size of a is", L.size)

Dimensions of a are: 1
Shape of a is (10,)
Size of a is 10


In [36]:
# Creating an Empty Array using empty_like Function
# np.empty() creates an array with random values
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
Empty_arr=np.empty([3,5])
Empty_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
print ("Dimensions of a are:", Empty_arr.ndim)
print ("Shape of a is", Empty_arr.shape)
print ("Size of a is", Empty_arr.size)

Dimensions of a are: 2
Shape of a is (3, 5)
Size of a is 15


In [39]:
# ***4. Create an array with random number of normal distribution from 0 to 1, excludes 1
# np.random.rand(5) # one dimensional
# random.rand(d0, d1, ..., dn), do, d1...denotes  dimension 0, 1,2 and so on 
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

#Parameters
#d0, d1, …, dnint, optional
#The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

#Returns outndarray, shape (d0, d1, ..., dn) Random values.

In [40]:
# ***The random module's np.random.rand() method returns a random float between 0 and 1.

In [41]:
 np.random.rand(5) # dimension 0 with random numbers 5

array([0.36072202, 0.31866257, 0.11196109, 0.52302401, 0.29458414])

In [42]:
 np.random.rand(5)

array([0.17177388, 0.3217735 , 0.3844988 , 0.87234215, 0.83004596])

In [43]:
 np.random.rand(5)  # uniform distribution [0,1)

array([0.27520345, 0.81005582, 0.9105518 , 0.83836017, 0.35917848])

In [44]:
# Each time when you run  np.random.rand(5) it will give you a different array of 5 elements between 0 and 1 , 1 excluded

In [45]:
Rand_arr =np.random.rand(2, 10) # 2x10 dimensional array with 10 numbers  between 0 and 1
Rand_arr

array([[0.50839264, 0.56048976, 0.98262768, 0.5590839 , 0.98198258,
        0.2219974 , 0.66512012, 0.95785683, 0.22288651, 0.81859269],
       [0.00684485, 0.05256403, 0.26343109, 0.56177976, 0.62517979,
        0.7495593 , 0.32947323, 0.62142582, 0.55061144, 0.29973415]])

In [46]:
print ("Dimensions of a are:", Rand_arr.ndim)
print ("Shape of a is", Rand_arr.shape)
print ("Size of a is", Rand_arr.size)

Dimensions of a are: 2
Shape of a is (2, 10)
Size of a is 20


In [47]:
Rand_arr1=np.random.rand(2, 3,5) # 2 x3x5
Rand_arr1

array([[[0.12599239, 0.83652005, 0.10932737, 0.3391921 , 0.06952523],
        [0.92694013, 0.01546008, 0.33395972, 0.75831051, 0.18481854],
        [0.45808833, 0.55230915, 0.02607844, 0.13394266, 0.0996577 ]],

       [[0.38272655, 0.01084894, 0.65692303, 0.99444968, 0.25997457],
        [0.57600274, 0.40162596, 0.78563867, 0.12420776, 0.7664676 ],
        [0.69122824, 0.04713372, 0.94400352, 0.44876634, 0.88324909]]])

In [48]:
print ("Dimensions of a are:", Rand_arr1.ndim)
print ("Shape of a is", Rand_arr1.shape)
print ("Size of a is", Rand_arr1.size)

Dimensions of a are: 3
Shape of a is (2, 3, 5)
Size of a is 30


In [49]:
Rand_arr2=np.random.rand(2, 3,5,4)
Rand_arr2

array([[[[0.95486196, 0.4089546 , 0.07832301, 0.41758967],
         [0.04091685, 0.4209588 , 0.59801746, 0.02535836],
         [0.03272249, 0.70473966, 0.70809372, 0.39682022],
         [0.37745316, 0.09756689, 0.66355782, 0.43542847],
         [0.39071343, 0.05974535, 0.76707933, 0.50950827]],

        [[0.38056924, 0.8515938 , 0.26228204, 0.45476003],
         [0.90785784, 0.29371052, 0.10167196, 0.87177708],
         [0.9114324 , 0.52903121, 0.29026325, 0.60560489],
         [0.49303424, 0.67188764, 0.57529321, 0.74025138],
         [0.66670046, 0.0299164 , 0.38574918, 0.72708731]],

        [[0.06730599, 0.61774024, 0.59758494, 0.87710547],
         [0.90724937, 0.8952059 , 0.68895009, 0.43275492],
         [0.08667885, 0.34516052, 0.4742161 , 0.4542651 ],
         [0.72005069, 0.81938444, 0.81885581, 0.96323792],
         [0.35988535, 0.03788892, 0.23707247, 0.27539707]]],


       [[[0.89156213, 0.25604565, 0.81013463, 0.44926809],
         [0.10526656, 0.22199665, 0.78832606, 0.

In [50]:
print ("Dimensions of a are:", Rand_arr2.ndim)
print ("Shape of a is", Rand_arr2.shape)
print ("Size of a is", Rand_arr2.size)

Dimensions of a are: 4
Shape of a is (2, 3, 5, 4)
Size of a is 120


In [51]:
# np.random.randn()
#random.randn(d0, d1, ..., dn)
#Return a sample (or samples) from the “standard normal” distribution.
#Parameters
#d0, d1, …, dnint, optional
#The dimensions of the returned array, must be non-negative. 
#If no argument is given a single Python float is returned.

#Returns
#ndarray or float
# A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, 
#or a single such float if no parameters were supplied.

#Note:  randn generates an array of shape (d0, d1, ..., dn), 
#filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [52]:
# Example:
np.random.randn()   # 

2.3293237511261595

In [53]:
np.random.randn(2) # return a 2 dimensional standard normal distribution or a Gaussian

               # distribution

array([-1.37607503,  0.78160811])

In [54]:
np.random.randn(2,3,4)

array([[[-2.05892911, -0.65472112,  0.07601311, -0.03627462],
        [-1.26063748, -0.34523789, -1.53093654, -0.80434745],
        [ 1.17947228,  0.40032339,  0.44906695,  0.84178261]],

       [[-0.02276881,  1.40361239, -0.09054117,  0.13163269],
        [ 1.01514124,  0.22748611, -0.20336459,  0.62219956],
        [-0.63093106, -0.74597999, -1.2560131 , -1.45646617]]])

In [55]:
# The np.random.randint(num,size=) method takes a size parameter where you can specify the shape of an array.

In [56]:
Randint_arr=np.random.randint(10,size=(2,2)) # generate any 10 numbers of size 2x2
Randint_arr

array([[9, 6],
       [3, 1]])

In [57]:
print ("Dimensions of a are:", Randint_arr.ndim)
print ("Shape of a is", Randint_arr.shape)
print ("Size of a is", Randint_arr.size)

Dimensions of a are: 2
Shape of a is (2, 2)
Size of a is 4


In [58]:
Randint_arr1=np.random.randint(20, size=(2,3,2))
Randint_arr1

array([[[ 2,  5],
        [ 3,  5],
        [19,  9]],

       [[15,  5],
        [14, 13],
        [15,  5]]])

In [59]:
print ("Dimensions of a are:", Randint_arr1.ndim)
print ("Shape of a is", Randint_arr1.shape)
print ("Size of a is", Randint_arr1.size)

Dimensions of a are: 3
Shape of a is (2, 3, 2)
Size of a is 12


In [60]:
np.random.randint(50) # return one number of the range up to 50

29

In [61]:
np.arange(50) # return 50 numbers up to 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [62]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [63]:
np.random.choice([1,2,3,4],size=(2,3))
# the choice method generates a ramdom array with one number/numbers
# out of the given list with the given size

array([[2, 2, 3],
       [4, 4, 3]])

In [64]:
np.random.choice(30, size=(2,2)) # return a random number/or array from 0 to 30 similar to randint method

array([[12,  1],
       [27,  0]])

In [65]:
np.random.randint(30, size=(2,2)) # return a random array from 0 to 30 with size =(2,2)

array([[27, 23],
       [27, 21]])

In [67]:
arr_range= np.arange(25).reshape(5,5)
arr_range


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Useful methods and attributes: shape, dtype, min(), max(), argmin(index of the max), argmax, ndim, size

In [69]:
arr_range.shape

(5, 5)

In [70]:
arr_range.size

25

In [71]:
arr_range.dtype

dtype('int32')

In [75]:
arr_range.ndim

2

In [76]:
arr_range.min()  # min() method

0

In [79]:
arr_range.argmin()  # index of the min

0

In [80]:
arr_range.max()

24

In [81]:
arr_range.argmax()

24

In [98]:
import numpy as np
from numpy.random import randint
from numpy.random import choice

In [95]:
randint(10, size=(2,3))  # similar to random.choice

array([[4, 0, 1],
       [5, 0, 7]])

In [99]:
choice(10, (2,3))

array([[5, 8, 9],
       [7, 1, 4]])

In [ ]:
## *** Conclusion: how to create a numpy array either by 
# 1.  casting a list to a higher array or
# 2. by using  one of the built in functions for a Numpy arrays such as arr.zeros and ones linspace and eye and

# 3. also the random generation methods you call np.random.rand() and then np.random.randn() and or some

# of the other random methods  np.random.randint().

In [ ]:
### Useful methods and attributes for a numpy array:
# 1. methods: reshape(), min(), max(), argmin(), argmax()
2. attributes: shape, dtype, ndim, size