In [1]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]  # or b= a[0:2,1:3]  keeping arrays indexed from first row to 2nd row 0:1 and columns from 1 to 2nd 1:3 last number is not included


print(a)
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [2]:
b=a[0:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [3]:
print (a[0,1]) # in the array a, the element in the index of first row and 2nd column

2


In [4]:
print(np.shape(b)) # 2x 2 matrix or arrays

(2, 2)


In [5]:
print(np.shape(a))  # 3x3 matrix or arrays

(3, 4)


In [6]:
print(np.size(a)) # how many elements in the array a

12


In [7]:
np.size(b)

4

In [8]:
np.shape(b)

(2, 2)

In [9]:
# Convert a np array to a dataframe:

import numpy as np
import pandas as pd
df = pd.DataFrame(data=a)
print(df)


   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12


In [10]:
# add the array to df as a column/rename the column of a dataframe use df.columns=
df.columns=["x","y","z","m"]
df
df.index=['a','b','c']
df

x   y   z   m
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [11]:
# Remame columns and index of a df from panda using df.columns=["","",""]  or df.index= ["",","]

In [12]:
# Create a data array A in numpy
A=np.array([[9,55,90, 0],[12,56,80,0],[15,67,125,0],[45,61,113,0],[46,67,180,0]])
A

array([[  9,  55,  90,   0],
       [ 12,  56,  80,   0],
       [ 15,  67, 125,   0],
       [ 45,  61, 113,   0],
       [ 46,  67, 180,   0]])

In [13]:
print(A)

[[  9  55  90   0]
 [ 12  56  80   0]
 [ 15  67 125   0]
 [ 45  61 113   0]
 [ 46  67 180   0]]


In [14]:
np.shape(A)  # number of rowx number of columns 5x4 shape

(5, 4)

In [15]:
type(A)

numpy.ndarray

In [16]:
np.size(A)   # 20 elements 

20

In [17]:
# Convert the array A to a dataframe df
import pandas as pd
df = pd.DataFrame(A)
print(df)


    0   1    2  3
0   9  55   90  0
1  12  56   80  0
2  15  67  125  0
3  45  61  113  0
4  46  67  180  0


In [18]:
# add the array to df as a column/rename the column of a dataframe use df.columns=
df.columns=["Age","Height(in)","Weight(lbs)","BMI"]

df.index=['Elina','Brain','Vince','Lonnie','CJ']
df

Age  Height(in)  Weight(lbs)  BMI
Elina     9          55           90    0
Brain    12          56           80    0
Vince    15          67          125    0
Lonnie   45          61          113    0
CJ       46          67          180    0

In [19]:
# Finding BMI for each person
# BMI=weight (kg)/height (meter squared)
# need to change height from in to meter: 
# 1 in= 0.0254 meter
# so "Height(meter)= Height(in)*0.0254
df["Height(meter)"]=df['Height(in)']*0.0254
df.head()

Age  Height(in)  Weight(lbs)  BMI  Height(meter)
Elina     9          55           90    0         1.3970
Brain    12          56           80    0         1.4224
Vince    15          67          125    0         1.7018
Lonnie   45          61          113    0         1.5494
CJ       46          67          180    0         1.7018

In [20]:
# change "Weight(lbs)" to "Weight(kg)"
# 1 lb= 0.4536 kg
# so "Weight(kg)" = "Weight(lbs)"*0.4536
df["Weight(kg)"] =df["Weight(lbs)"]*0.4536
df.head()

Age  Height(in)  Weight(lbs)  BMI  Height(meter)  Weight(kg)
Elina     9          55           90    0         1.3970     40.8240
Brain    12          56           80    0         1.4224     36.2880
Vince    15          67          125    0         1.7018     56.7000
Lonnie   45          61          113    0         1.5494     51.2568
CJ       46          67          180    0         1.7018     81.6480

In [21]:
# Now calculate the BMI :BMI=weight (kg)/height (meter squared) using for loop 
i=1
for i in range(5):
    BMI_new=df["Weight(kg)"]/(df["Height(meter)"]**2)
print(BMI_new)

Elina     20.918124
Brain     17.935750
Vince     19.577896
Lonnie    21.351303
CJ        28.192170
dtype: float64


In [22]:
# Bingo! 
# Now replace BMI with BMI_new
# using df.replace(old, new)
# Example: df["bore"].replace(np.nan,avg_bore,inplace=True)  replacing the oldvalues in "bore" with the new values
df["BMI"].replace(0,BMI_new,inplace=True)
df.head()

Age  Height(in)  Weight(lbs)        BMI  Height(meter)  Weight(kg)
Elina     9          55           90  20.918124         1.3970     40.8240
Brain    12          56           80  17.935750         1.4224     36.2880
Vince    15          67          125  19.577896         1.7018     56.7000
Lonnie   45          61          113  21.351303         1.5494     51.2568
CJ       46          67          180  28.192170         1.7018     81.6480

In [23]:
# Swapping two columns
# Example: cols = list(df.columns)
# a, b = cols.index('LastName'), cols.index('MiddleName')
# cols[b], cols[a] = cols[a], cols[b]
# df = df[cols]

In [24]:
cols=list(df.columns)
a,b,c=cols.index("BMI"),cols.index("Height(meter)"),cols.index("Weight(kg)")
cols[c],cols[b],cols[a]=cols[a],cols[b],cols[c]
df=df[cols]
df.head()

Age  Height(in)  Weight(lbs)  Weight(kg)  Height(meter)        BMI
Elina     9          55           90     40.8240         1.3970  20.918124
Brain    12          56           80     36.2880         1.4224  17.935750
Vince    15          67          125     56.7000         1.7018  19.577896
Lonnie   45          61          113     51.2568         1.5494  21.351303
CJ       46          67          180     81.6480         1.7018  28.192170