# Python Indexing, Slicing and Selection

### Indexing: to access an array element by its index number
#### In python the index number starts with 0, meaning the first element has index 0 the last has index -1
####  sytax: arr[index number] for 1-d arr[]

In [3]:
import numpy as np

In [4]:
# creating a 1 -D ndarray using arange:
arr=np.arange(9)  # size 9
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# accesing the 2nd element:
arr[1]

1

In [6]:
#accessing the last element
arr[-1]

8

### Slicing: taking elements from one given index to another given index.

#### pass slice instead of index like this: [start:end]. end index number is excluded

#### We can also define the step, syntax  like this: [start: end: step].

#### If we don't pass start its considered 0

#### If we don't pass end its considered length of array in that dimension

#### If we don't pass step its considered 1

In [7]:
# take the elements from 2nd to 6th
arr[1:6]

array([1, 2, 3, 4, 5])

In [8]:
# get the elements from last to the 4th
arr=np.arange(15)

arr[3:15]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# creating a 2-D  array
arr=np.arange(20).reshape((4,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
# Indexing: accessing the 3rd element on the 2nd row
arr[1,2]  # arr[row,column] for 1-D

7

In [11]:
arr[1][2]

7

In [12]:
# Slicing: get elements from the first two row and last 3 columns
arr[:2, 2:]  # arr[row stars:row ends: column stars: column ends] for 2-D

array([[2, 3, 4],
       [7, 8, 9]])

In [13]:
arr[:2]  # first two rows

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Creating a 3-D array
arr=np.arange(3,50,2).reshape(2,6,2)  # column 2 row 6 dimention 2
arr


array([[[ 3,  5],
        [ 7,  9],
        [11, 13],
        [15, 17],
        [19, 21],
        [23, 25]],

       [[27, 29],
        [31, 33],
        [35, 37],
        [39, 41],
        [43, 45],
        [47, 49]]])

In [15]:
arr[1][1][1] # 2nd dimention 2nd element on 2nd row

33

In [20]:
# Lets try arr[dim , R , C ,]
arr[1,:3,:1]  # 2nd dimension, first 3 rows first column

array([[27],
       [31],
       [35]])

In [30]:
arr[1][:4] # subsequence in an array arr[dim][row, Column][row,column]

array([[27, 29],
       [31, 33],
       [35, 37],
       [39, 41]])

In [17]:
arr[0][1][0] # 1st dimention 2nd row 1st column

7

In [31]:
# how to access 9?
arr[0][1]    # ist dimention 2nd element from 2nd row  arr[dim][row][column]

array([7, 9])

In [19]:
arr[1][0][0]  # arr[dimention=2][row=1st][column=1st]

27

In [57]:
arr[1][1][0]

31

In [58]:
arr[1][3][0]  # arr[d=2nd]prow=4th][C=1st]

39

In [68]:
# Select elements from an array
arr=np.arange(1,30,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [69]:
#select the first 5 elements
arr[0:5]

array([1, 3, 5, 7, 9])

In [70]:
#change them to a specific number by assigning a new value
#arr[0:5]=20
#arr

In [71]:
# make a copy of the new array
x= arr.copy()
y=arr.view()
arr[0:5]=20
print(arr)
print(x)  # and any changes made to the original array will not affect the copy
print(y) # any changes to the original will affect the view

[20 20 20 20 20 11 13 15 17 19 21 23 25 27 29]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[20 20 20 20 20 11 13 15 17 19 21 23 25 27 29]


# The Difference Between Copy and View
#The main difference between a copy and a view of an array is that the copy is a new array, 
#and the view is just a view of the original array.

#The copy owns the data and any changes made to the copy will not affect original array,
#and any changes made to the original array will not affect the copy.

#The view does not own the data and any changes made to the view will affect the original array,
#and any changes made to the original array will affect the view.

In [73]:
arr= np.arange(15,50,2)
arr

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49])

In [74]:
x=arr.copy()
y=arr.view()
x[3]=5
print(x)  #changes to the copy won't change the original and view
print(y)
print(arr)

[15 17 19  5 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [75]:
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()
y[2]=5  # the change made to the view affect the original
print(x)
print(y) 
print(arr)

[1 2 3 4]
[1 2 5 4]
[1 2 5 4]


In [ ]:
# copies owns the data, and views does not own the data, but how can we check this?

#Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object.

In [76]:
print(x.base) # Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object.

print(y.base)

None
[1 2 5 4]


In [36]:
# select elements by using boolean

arr= np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
Bool_arr=arr>6  # setting condition
Bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [38]:
# now make selection
arr[Bool_arr]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
# or you could do it as:
arr[arr<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr=np.array([2,5,6,10,15,18], dtype="i")

print(arr.dtype)
arr%5


int32


array([2, 0, 1, 0, 0, 3], dtype=int32)

In [41]:
arr[arr%5==0]

array([ 5, 10, 15], dtype=int32)

In [45]:
# select
arr=np.array([1,2,3,4,5,6,7,10,15,20,24,25])
arr[(arr[arr>5]) & (arr[arr<105])]

ValueError: operands could not be broadcast together with shapes (7,) (12,) 

# Data Types in NumPy
#NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

#Below is a list of all data types in NumPy and the characters used to represent them.

#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float
#m - timedelta
#M - datetime
#O - object
#S - string
#U - unicode string
#V - fixed chunk of memory for other type ( void )


#### Create array with defined datatype include dtype="i" for integer in the array function np.array([], dtype="S")
####  check datatype using print(arr.dtype)
####  change the datatype by newarr=arr.astype("i")

In [98]:
# Create an array with defined datatype
arr= np.array(["1","2","3"], dtype="i")
arr

array([1, 2, 3], dtype=int32)

In [99]:
# check datatype
print(arr.dtype)

int32


In [100]:
type(arr)

numpy.ndarray

In [101]:
# change datatype
newarr=arr.astype("f")
newarr

array([1., 2., 3.], dtype=float32)